name: EDI Infrastructure CD

on:
  push:
    branches:
      - main
    paths:
      - edi/**
      - .github/workflows/edi-ci.yml
      - .github/workflows/edi-cd.yml
      - .github/workflows/infrastructure-build-prerelease.yml

jobs:
  #
  # CD Infrastructure
  #

  infrastructure_promote_prerelease:
    uses: Energinet-DataHub/.github/.github/workflows/promote-prerelease.yml@v9
    with:
      RELEASE_NAME_PREFIX: edi_infrastructure

  #
  # Dispatch deployment request
  #

  dispatch_deploment_event:
    runs-on: ubuntu-latest
    needs: infrastructure_promote_prerelease
    steps:
      - name: Find associated pull request
        uses: Energinet-DataHub/.github/.github/actions/find-related-pr-number@v9
        id: find_pull_request

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT_TOKEN }}
          repository: '${{ secrets.DEPLOYMENT_REPOSITORY_PATH }}'
          event-type: 'edi-deployment-request-infrastructure'
          client-payload: '{"infrastructure_pr": "${{ steps.find_pull_request.outputs.pull_request_number }}"}'

  #
  # Send notification to teams channel if deployment dispatch failed
  #

  dispatch_failed:
    needs: [
      infrastructure_promote_prerelease,
      dispatch_deploment_event,
    ]
    if: |
      always() &&
      contains(needs.*.result, 'failure')
    uses: Energinet-DataHub/.github/.github/workflows/notify-team.yml@v9
    with:
      TEAM_NAME: 'Batman'
      SUBJECT: 'Deployment dispatch failed: Infrastructure - EDI'
    secrets: inherit