name: Sauron Health Checks API Infrastructure CD

on:
  push:
    branches:
      - main
    paths:
      - sauron-healthchecks-api/**
      - .github/workflows/sauron-healthchecks-api-cd.yml
      - .github/workflows/infrastructure-build-prerelease.yml
      - .github/workflows/infrastructure-validate.yml

jobs:
  reusable_cd:
    uses: ./.github/workflows/reusable-cd.yml
    with:
      release_name_prefix: sauron_healthchecks_api_infrastructure
      event_type: sauron-healthchecks-api-deployment-request-infrastructure
      team_name: TeamFusion
    secrets: inherit
