name: DH UI Infrastructure CI

on:
  pull_request:
    branches:
      - main
    paths:
      - ui/**
      - .github/workflows/ui-ci.yml
      - .github/workflows/ui-cd.yml
      - .github/workflows/infrastructure-build-prerelease.yml
      - .github/actions/terraform-validate/*

jobs:
  #
  # Verify, build and create pre-release version of infrastructure code
  # Branch policy status check
  #
  infrastructure_ci:
    uses: Energinet-DataHub/dh3-infrastructure/.github/workflows/infrastructure-build-prerelease.yml@main
    with:
      RELEASE_NAME_PREFIX: 'ui_infrastructure'
      INFRASTRUCTURE_PATH: './ui/terraform'
    secrets:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
